''' Little GNU/Linux Assistant Setup
    
    This little file sets up the Little Assistant, creates a sources file for other files to reference.'''
import os as sh
x = "Welcome to your new assistant." 
y = "Let's get you all setup."
createFile = 'touch variables.py' 
# function for sleeping the system 
def sleepSys():
    slp = 'sleep 1' 
    sh.system(slp)
# function for getting name
def getName():
    a = "Let's get to know each other."
    b = "What is your name? Type it below:\n"
    print(a)
    userName = input(b)
    print(f'It is really nice to meet you, {userName}.')
    sh.system(f'echo "userName = '{userName}'" >> sources.py')
# function for getting location (In ZIP code form) 
def getZIP():
    weath = "I can get the weather and news for you."
    acc = "To display accurate results, I'll need your location to help me."
    zipq = "Can you type your ZIP code below?\n"
    print(weath)
    print(acc)
    zip_code = input(zipq)
    print(f'You said your zip code is {zip_code}. Is this correct?')
    yorn = "Please type Yes or No below:\n"
    correct = input(yorn)
    if (correct == "Yes"):
        print("Saving your information for you.")
        sh.system(f'echo "zip_code = {zip_code}" >> sources.py')
        print(f'ZIP code saved as {zip_code}.')
    else:
        print("Please input a valid zip code.")
# function for naming assistant
def name_buddy():
    one = "Want to give me a name?"
    two = "You can name me whatever you'd like." 
    three = "Please type in my new name below:\n"
    print(one)
    print(two)
    asstName = input(three)
    print(f'I think I like the name {asstName}. Thanks!')
    print("Saving my new information...")
    sh.system(f'echo "asstName = '{asstName}'" >> sources.py')
    print("Information saved.")
# function for "launch or leave." if you want to leave, you can, or you can launch into the main menu
def lol():
    lol1 = "What do you want to do now? Here are your options:"
    lol_opts = ["1 - Go to Main Menu", "2 - Exit"]
    ch1 = "So, what will your choice be? Please type the number of the choice you want."
    mm_go = "Launching the main menu!"
    xIt = "Exiting the program!" 
    def mm(): # internal function for launching into the main menu 
        menuLaunch = 'python3 mainMenu.py'
        sh.system(menuLaunch) 
    print(lol1) 
    for lolz in lol_opts:
        print(lolz)
    lol_opts[0], lol_opts[1] = 1, 2
    lol_opts[0], lol_opts[1] = str(lol_opts[0]), str(lol_opts[1])
    pick = input(ch1)
    if (pick == lol_opts[0]):
        print(mm_go)
        sleepSys()
        mm()
    elif (pick == lol_opts[1]):
        print(xIt) 
        exit()
    else:
        inval = "Invalid option chosen."
        print(inval) 
        print(xIt) 
        exit()
# progam begins here
print(x)
print(y)
def autogen():  # quick function for creating the sources.py file for population
    sh.system(createFile) 
    auto = 'echo "# this file is automatically generated and populated with variables" >> sources.py'
    sh.system(auto) # generate the file
def copySrcToLib(): # quick function for copying the source file to library 
    copyFile = 'cp sources.py library' 
    sh.system(copyFile)
autogen() # generate the sources.py file
getName() # fill in the userName variable
name_buddy() # fill in the asstName variable
getZIP() # fill in the zip_code variable
copySrcToLib() # send a copy of the sources.py file to the library folder for reference
print("I think I got everything I need.")
print("Thanks!")
lol() # launch or leave the program