// Porting LLA to C. 
// Will update more in the comments later. 
#include <stdio.h> 
#include <stdlib.h>
#include <string.h>
// * * * FUNCTIONS * * * 
void SLEEP_SYS() {
    // sleeps sys 1 sec 
    system("sleep 1"); 
}
void COPY_DONE_NOTIF() {
    // notifies the user that var info was saved to sources.txt
    system("notify-send 'Little Linux Assistant' 'Your information was saved to sources.txt.'"); 
}
void MM_LAUNCH_NOTIF() {
    // runs when user selects to launch the main menu. 
    system("notify-send 'Little Linux Assistant' 'Launching the main menu.'");
}
void EXITING_PROG_NOTIF() {
    // when the user selects to finish
    system("notify-send 'Little Linux Assistant' 'You chose to exit the program.'"); 
}
void INVALID_EXITING_NOTIF() {
    // runs when the user selects an invalid option
    system("notify-send 'Little Linux Assistant' 'Invalid option selected. Exiting.'"); 
}
// program entry point
void main() {
    printf("Welcome to your new assistant.\n"); 
    SLEEP_SYS(); 
    printf("Let's get you all set up.\n");
    SLEEP_SYS();  
    printf("Let's get to know each other.\n");
    SLEEP_SYS();
    // first, we get the user's name and save it to var 'username' 
    printf("What is your name? Type it below: \n");
    char username[15]; 
    scanf("%s", &username); 
    printf("Nice to meet you, %s!\n", username);
    // next, we get the user's ZIP code for weather, save it to var 'zip_code' 
    printf("I can get the weather and news for you.\n");
    SLEEP_SYS(); 
    printf("To display accurate results, I will need your location to help me.\n"); 
    SLEEP_SYS();
    printf("Can you type your ZIP code below? \n"); 
    int zip_code; 
    scanf("%d", &zip_code); 
    printf("You said your ZIP code is %d. Is this correct?\n", zip_code);
    SLEEP_SYS();
    printf("Please type 'Yes' or 'No' below: \n");
    char correct[3]; 
    scanf("%s", &correct);
    if (strcmp(correct, "Yes") == 0) {
        printf("ZIP code will be saved as %d.\n", zip_code);
        SLEEP_SYS();
        printf("Moving on...\n"); 
    } else {
        printf("Please provide a valid ZIP code."); 
    }
    // allow the user to name the assistant
    printf("Want to give me a name?\n"); 
    SLEEP_SYS();
    printf("You can name me whatever you'd like.\n"); 
    SLEEP_SYS();
    printf("Please type in my new name below: \n"); 
    char asstName[10];
    scanf("%s", &asstName); 
    printf("I think I like the name %s. Thanks!\n", asstName); 
    SLEEP_SYS();
    printf("Saving all information to 'sources.txt'...\n");
    // save all of the information to a 'sources.txt' file for vars 
    char autogen[] = "# This file is automatically generated by Little Linux Assistant."; 
    FILE *fsrc;
    fsrc = fopen("sources.txt", "w");
    fprintf(fsrc, "%s\n", autogen);
    fprintf(fsrc, "%s\n", username);  // save the 'name' var 
    fprintf(fsrc, "%d\n", zip_code);  // save the 'zip_code' var
    fprintf(fsrc, "%s\n", asstName);  // save the 'asstName' var
    fclose(fsrc); // close the file
    printf("All information has been saved.\n");
    // now, we can copy the 'sources.txt' file to a 'sources.txt' file in /library
    void copySrcToLib() {
        // copies 'sources.txt' to 'library/sources.txt'
        system("mkdir library && sudo cp sources.txt /library/sources.txt");
    }
    copySrcToLib(); 
    COPY_DONE_NOTIF(); 
    printf("I think I have everything I need.\n");
    SLEEP_SYS();
    printf("Thanks!"); 
    SLEEP_SYS(); 
    void lol() {
        // 'launch or leave.' lets user launch to menu, or exit. 
        printf("What do you want to do now? Here are your options:\n");
        // make an array of options and print them 
        char *options[] = {"1 - Launch to menu", "2 - Exit"};
        printf("%s\n %s\n", options[0], options[1]);
        // convert options to ints for the user to select 
        int opt1 = 1, opt2 = 2; 
        options[0] = opt1;
        options[1] = opt2;   
        printf("Please input the number corresponding to your choice below: \n"); 
        int pick;
        scanf("%d", &pick);
        /* If the user selects '1', we launch the main menu. 
        If the user selects '2', we exit the program. */ 
        if (pick == 1) {
            MM_LAUNCH_NOTIF(); 
            printf("Launching the main menu!\n"); 
            void MAINMENULAUNCH() {
                // launches into the main menu. 
                system("./mainMenu.out");
            }
            MAINMENULAUNCH(); 
        } else if (pick == 2) {
            EXITING_PROG_NOTIF(); 
            printf("Exiting the program!\n");
            exit(0);
        } else {
            INVALID_EXITING_NOTIF(); 
            printf("Invalid input. Exiting the program.\n");
            exit(0);
        }; 
    };  
    lol();
}